name: Build and deploy

on:
  push:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
      id: extract_branch

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # cache node_modules
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    # cache nextjs files
    - uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

    - name: yarn install, build, and test
      run: |
        yarn install
        yarn build
        yarn export

    - name: Netlify deploy
      run: |
        yarn global add netlify-cli
        "$(yarn global bin)/netlify" --telemetry-disable

        # Determine if we should add the prod flag
        if [ "${{ steps.extract_branch.outputs.branch }}" = "master" ]; then is_prod="--prod"; else is_prod=""; fi

        # Deploy
        "$(yarn global bin)/netlify" deploy --dir=out ${is_prod}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
