name: Build and deploy

on:
  push:
    branches:
      - master
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # cache node_modules
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: yarn install, build, and test
      run: |
        yarn install
        yarn build
        yarn export

    - name: Netlify deploy
      run: |
        yarn global add netlify-cli
        "$(yarn global bin)/netlify" --telemetry-disable
        "$(yarn global bin)/netlify" deploy --dir=out --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
